2024-05-31 22:20:27.380278+09:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLNonTransientException: 不明なデータ型: "PRIMARY"
Unknown data type: "PRIMARY"; SQL statement:
create table TASKS (
    TASK_ID primary key auto_increment,
    USER_ID not null references USERS(USER_ID),
    TASK_GROUP not null,
    TASK_CONTENT not null,
    TANTATIVE_START_DATETIME not null,
    TANTATIVE_END_DATETIME not null,
    START_DATETIME,
    END_DATETIME
) [50004-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:566)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.command.Parser.readIfDataType1(Parser.java:5866)
	at org.h2.command.Parser.readIfDataType(Parser.java:5704)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:5686)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:5565)
	at org.h2.command.Parser.parseTableColumnDefinition(Parser.java:8999)
	at org.h2.command.Parser.parseCreateTable(Parser.java:8939)
	at org.h2.command.Parser.parseCreate(Parser.java:6404)
	at org.h2.command.Parser.parsePrepared(Parser.java:666)
	at org.h2.command.Parser.parse(Parser.java:592)
	at org.h2.command.Parser.parse(Parser.java:564)
	at org.h2.command.Parser.prepareCommand(Parser.java:483)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:639)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:559)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1166)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:245)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:231)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1345)
	at org.h2.server.web.WebApp.query(WebApp.java:1143)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1109)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1096)
	at org.h2.server.web.WebThread.process(WebThread.java:190)
	at org.h2.server.web.WebThread.run(WebThread.java:103)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-05-31 22:20:27.388383+09:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "TASKS" not found (this database is empty); SQL statement:
insert into TASKS (USER_ID, TASK_GROUP, TASK_CONTENT, TANTATIVE_START_DATETIME, TANTATIVE_END_DATETIME)
values ('minato', 'メール', '午前中分メール対応', '2024-6-2 09:00:00','2024-6-2 09:15:00') [42104-224]
2024-05-31 22:21:20.235958+09:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLNonTransientException: 不明なデータ型: "PRIMARY"
Unknown data type: "PRIMARY"; SQL statement:
create table TASKS (
    TASK_ID primary key auto_increment,
    USER_ID not null references USERS(USER_ID),
    TASK_GROUP not null,
    TASK_CONTENT not null,
    TANTATIVE_START_DATETIME not null,
    TANTATIVE_END_DATETIME not null,
    START_DATETIME,
    END_DATETIME
) [50004-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:566)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.command.Parser.readIfDataType1(Parser.java:5866)
	at org.h2.command.Parser.readIfDataType(Parser.java:5704)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:5686)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:5565)
	at org.h2.command.Parser.parseTableColumnDefinition(Parser.java:8999)
	at org.h2.command.Parser.parseCreateTable(Parser.java:8939)
	at org.h2.command.Parser.parseCreate(Parser.java:6404)
	at org.h2.command.Parser.parsePrepared(Parser.java:666)
	at org.h2.command.Parser.parse(Parser.java:592)
	at org.h2.command.Parser.parse(Parser.java:564)
	at org.h2.command.Parser.prepareCommand(Parser.java:483)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:639)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:559)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1166)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:245)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:231)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1345)
	at org.h2.server.web.WebApp.query(WebApp.java:1143)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1109)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1096)
	at org.h2.server.web.WebThread.process(WebThread.java:190)
	at org.h2.server.web.WebThread.run(WebThread.java:103)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-05-31 22:21:20.235958+09:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "TASKS" が見つかりません
Table "TASKS" not found; SQL statement:
insert into TASKS (USER_ID, TASK_GROUP, TASK_CONTENT, TANTATIVE_START_DATETIME, TANTATIVE_END_DATETIME)
values ('minato', 'メール', '午前中分メール対応', '2024-6-2 09:00:00','2024-6-2 09:15:00') [42102-224]
2024-05-31 22:33:05.511073+09:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: 列 "TASK_ID" が見つかりません
Column "TASK_ID" not found; SQL statement:
create table TASKS (
    TASK_ID integer primary key auto_increment,
    USER_ID varchar(10) not null references USERS(USER_ID),
    TASKGROUP_ID integer not null references TASKGROUP(TASK_ID),
    TASK_CONTENT varchar(255) not null,
    TANTATIVE_START_DATETIME datetime not null,
    TANTATIVE_END_DATETIME datetime not null,
    START_DATETIME datetime,
    END_DATETIME datetime
) [42122-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:514)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.table.Table.getColumn(Table.java:759)
	at org.h2.table.IndexColumn.mapColumns(IndexColumn.java:184)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:219)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:74)
	at org.h2.command.ddl.AlterTable.update(AlterTable.java:46)
	at org.h2.command.ddl.CommandWithColumns.createConstraints(CommandWithColumns.java:83)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:134)
	at org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at org.h2.command.Command.executeUpdate(Command.java:256)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:262)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:231)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1345)
	at org.h2.server.web.WebApp.query(WebApp.java:1143)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1109)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1096)
	at org.h2.server.web.WebThread.process(WebThread.java:190)
	at org.h2.server.web.WebThread.run(WebThread.java:103)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-05-31 22:33:05.511073+09:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "TASKS" が見つかりません
Table "TASKS" not found; SQL statement:
insert into TASKS (USER_ID, TASK_GROUP, TASK_CONTENT, TANTATIVE_START_DATETIME, TANTATIVE_END_DATETIME)
values ('minato', '1', '午前中分メール対応', '2024-6-2 09:00:00','2024-6-2 09:15:00') [42102-224]
2024-05-31 22:34:25.047064+09:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: 列 "TASK_ID" が見つかりません
Column "TASK_ID" not found; SQL statement:
create table TASKS (
    TASK_ID integer primary key auto_increment,
    USER_ID varchar(10) not null references USERS(USER_ID),
    TASKGROUP_ID integer not null references TASKGROUP(TASK_ID),
    TASK_CONTENT varchar(255) not null,
    TANTATIVE_START_DATETIME datetime not null,
    TANTATIVE_END_DATETIME datetime not null,
    START_DATETIME datetime,
    END_DATETIME datetime
) [42122-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:514)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.table.Table.getColumn(Table.java:759)
	at org.h2.table.IndexColumn.mapColumns(IndexColumn.java:184)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:219)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:74)
	at org.h2.command.ddl.AlterTable.update(AlterTable.java:46)
	at org.h2.command.ddl.CommandWithColumns.createConstraints(CommandWithColumns.java:83)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:134)
	at org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at org.h2.command.Command.executeUpdate(Command.java:256)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:262)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:231)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1345)
	at org.h2.server.web.WebApp.query(WebApp.java:1143)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1109)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1096)
	at org.h2.server.web.WebThread.process(WebThread.java:190)
	at org.h2.server.web.WebThread.run(WebThread.java:103)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-05-31 22:34:25.048061+09:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "TASKS" が見つかりません
Table "TASKS" not found; SQL statement:
insert into TASKS (USER_ID, TASKGROUP_ID, TASK_CONTENT, TANTATIVE_START_DATETIME, TANTATIVE_END_DATETIME)
values ('minato', '1', '午前中分メール対応', '2024-6-2 09:00:00','2024-6-2 09:15:00') [42102-224]
2024-06-05 22:08:02.388933+09:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: "CONSTRAINT_4BE" が依存しているため、"USERS" をドロップすることはできません
Cannot drop "USERS" because "CONSTRAINT_4BE" depends on it; SQL statement:
drop table USERS [90107-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:644)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.command.ddl.DropTable.prepareDrop(DropTable.java:108)
	at org.h2.command.ddl.DropTable.update(DropTable.java:133)
	at org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at org.h2.command.Command.executeUpdate(Command.java:256)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:262)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:231)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1345)
	at org.h2.server.web.WebApp.query(WebApp.java:1143)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1109)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1096)
	at org.h2.server.web.WebThread.process(WebThread.java:190)
	at org.h2.server.web.WebThread.run(WebThread.java:103)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-06-05 22:08:58.151711+09:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: "CONSTRAINT_4BE" が依存しているため、"USERS" をドロップすることはできません
Cannot drop "USERS" because "CONSTRAINT_4BE" depends on it; SQL statement:
drop table USERS [90107-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:644)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.command.ddl.DropTable.prepareDrop(DropTable.java:108)
	at org.h2.command.ddl.DropTable.update(DropTable.java:133)
	at org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at org.h2.command.Command.executeUpdate(Command.java:256)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:262)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:231)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1345)
	at org.h2.server.web.WebApp.query(WebApp.java:1143)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1109)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1096)
	at org.h2.server.web.WebThread.process(WebThread.java:190)
	at org.h2.server.web.WebThread.run(WebThread.java:103)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-06-05 22:08:58.160795+09:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "USERS" はすでに存在します
Table "USERS" already exists; SQL statement:
create table USERS (
    USER_ID varchar(10) primary key,
    PASS varchar(40) not null,
    MAIL varchar(100) not null,
    USER_NAME varchar(40) not null,
    DATEOFBIRTH date not null
) [42101-224]
2024-06-05 22:08:58.160795+09:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: 列名 "USER_ID" が重複しています
Duplicate column name "USER_ID"; SQL statement:
insert into USERS (USER_ID, PASS, MAIL,USER_ID, DATEOFBIRTH)
values ('minato', '1234', 'yusuke.minato@miyabilonk.jp','湊　雄輔', '2001-05-01') [42121-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:514)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.command.Parser.parseColumnList(Parser.java:1177)
	at org.h2.command.Parser.parseInsert(Parser.java:1549)
	at org.h2.command.Parser.parsePrepared(Parser.java:719)
	at org.h2.command.Parser.parse(Parser.java:592)
	at org.h2.command.Parser.parse(Parser.java:564)
	at org.h2.command.Parser.prepareCommand(Parser.java:483)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:639)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:559)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1166)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:245)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:231)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1345)
	at org.h2.server.web.WebApp.query(WebApp.java:1143)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1109)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1096)
	at org.h2.server.web.WebThread.process(WebThread.java:190)
	at org.h2.server.web.WebThread.run(WebThread.java:103)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-06-05 22:10:29.037213+09:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "delete [*]table TASKS"; 期待されるステートメント "identifier"
Syntax error in SQL statement "delete [*]table TASKS"; expected "identifier"; SQL statement:
delete table TASKS [42001-224]
2024-06-05 22:11:36.379632+09:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: "CONSTRAINT_4BE" が依存しているため、"USERS" をドロップすることはできません
Cannot drop "USERS" because "CONSTRAINT_4BE" depends on it; SQL statement:
drop table users [90107-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:644)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.command.ddl.DropTable.prepareDrop(DropTable.java:108)
	at org.h2.command.ddl.DropTable.update(DropTable.java:133)
	at org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at org.h2.command.Command.executeUpdate(Command.java:256)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:262)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:231)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1345)
	at org.h2.server.web.WebApp.query(WebApp.java:1143)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1109)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1096)
	at org.h2.server.web.WebThread.process(WebThread.java:190)
	at org.h2.server.web.WebThread.run(WebThread.java:103)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-06-05 22:13:32.058977+09:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: 列名 "USER_ID" が重複しています
Duplicate column name "USER_ID"; SQL statement:
insert into USERS (USER_ID, PASS, MAIL,USER_ID, DATEOFBIRTH)
values ('minato', '1234', 'yusuke.minato@miyabilonk.jp','湊　雄輔', '2001-05-01') [42121-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:514)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.command.Parser.parseColumnList(Parser.java:1177)
	at org.h2.command.Parser.parseInsert(Parser.java:1549)
	at org.h2.command.Parser.parsePrepared(Parser.java:719)
	at org.h2.command.Parser.parse(Parser.java:592)
	at org.h2.command.Parser.parse(Parser.java:564)
	at org.h2.command.Parser.prepareCommand(Parser.java:483)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:639)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:559)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1166)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:245)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:231)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1345)
	at org.h2.server.web.WebApp.query(WebApp.java:1143)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1109)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1096)
	at org.h2.server.web.WebThread.process(WebThread.java:190)
	at org.h2.server.web.WebThread.run(WebThread.java:103)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-06-05 22:14:36.294870+09:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: 列 "TASK_ID" が見つかりません
Column "TASK_ID" not found; SQL statement:
create table TASKS (
    TASK_ID integer primary key auto_increment,
    USER_ID varchar(10) not null references USERS(USER_ID),
    TASKGROUP_ID integer not null references TASKGROUP(TASK_ID),
    TASK_CONTENT varchar(255) not null,
    TANTATIVE_START_DATETIME datetime not null,
    TANTATIVE_END_DATETIME datetime not null,
    START_DATETIME datetime,
    END_DATETIME datetime
) [42122-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:514)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.table.Table.getColumn(Table.java:759)
	at org.h2.table.IndexColumn.mapColumns(IndexColumn.java:184)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:219)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:74)
	at org.h2.command.ddl.AlterTable.update(AlterTable.java:46)
	at org.h2.command.ddl.CommandWithColumns.createConstraints(CommandWithColumns.java:83)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:134)
	at org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at org.h2.command.Command.executeUpdate(Command.java:256)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:262)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:231)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1345)
	at org.h2.server.web.WebApp.query(WebApp.java:1143)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1109)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1096)
	at org.h2.server.web.WebThread.process(WebThread.java:190)
	at org.h2.server.web.WebThread.run(WebThread.java:103)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-06-05 22:14:36.297128+09:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "TASKS" が見つかりません
Table "TASKS" not found; SQL statement:
insert into TASKS (USER_ID, TASKGROUP_ID, TASK_CONTENT, TANTATIVE_START_DATETIME, TANTATIVE_END_DATETIME)
values ('minato', '1', '午前中分メール対応', '2024-6-2 09:00:00','2024-6-2 09:15:00') [42102-224]
2024-06-08 22:26:49.588259+09:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "[*]TASKGROUP"; 期待されるステートメント "TRUNCATE"
Syntax error in SQL statement "[*]TASKGROUP"; expected "TRUNCATE"; SQL statement:
TASKGROUP [42001-224]
2024-06-08 22:31:42.409202+09:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: 列 "TENTATIVE_END_DATETIME" が見つかりません
Column "TENTATIVE_END_DATETIME" not found; SQL statement:
SELECT * FROM TASKS WHERE USER_ID = 'minato' AND REGISTER_DATE = '2024-06-08' ORDER BY TENTATIVE_END_DATETIME [42122-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:514)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:244)
	at org.h2.expression.ExpressionColumn.optimizeOther(ExpressionColumn.java:226)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:213)
	at org.h2.command.query.Select.prepareExpressions(Select.java:1170)
	at org.h2.command.query.Query.prepare(Query.java:218)
	at org.h2.command.Parser.prepareCommand(Parser.java:489)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:639)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:559)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1166)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:245)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:231)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1345)
	at org.h2.server.web.WebApp.query(WebApp.java:1143)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1109)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1096)
	at org.h2.server.web.WebThread.process(WebThread.java:190)
	at org.h2.server.web.WebThread.run(WebThread.java:103)
	at java.base/java.lang.Thread.run(Thread.java:1583)
